# Generated by Django 6.0.5 on 2026-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_phase812_hrms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.JSONField(blank=True, default=dict, help_text='Keys: annual, sick, used_annual, used_sick'),
        ),
    ]
