# Generated by Django 6.0.5 on 2026-06-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0003_expand_audit_action_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_company_created_idx',
        ),
    ]
