# Generated by Django 6.0.6 on 2026-06-19 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_task_management'),
        ('licensing', '0009_customer_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('developer', 'Developer'), ('support', 'Support'), ('customer_success', 'Customer Success'), ('finance', 'Finance'), ('sales', 'Sales')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('weekly_capacity', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='InternalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('infra', 'Infra'), ('security', 'Security'), ('escalation', 'Escalation')], default='bug', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sla_due', models.DateTimeField(blank=True, null=True)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='on_track', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_internal_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_tickets', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_tickets', to=settings.AUTH_USER_MODEL)),
                ('source_support_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_escalations', to='licensing.tenantsupportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.internalticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
