# Generated by Django 6.0.6 on 2026-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_sync_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past_Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
    ]
