# Generated by Django 6.0.5 on 2026-06-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_task_taskcomment'),
        ('recruitment', '0002_candidatedocument_deployment_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVisaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('documents_pending', 'Documents Pending'), ('documents_completed', 'Documents Completed'), ('submitted', 'Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deployed', 'Deployed')], default='new', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkVisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('visa_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workvisa.workvisacase')),
            ],
        ),
        migrations.CreateModel(
            name='WorkVisaTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visa_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workvisa.workvisacase')),
            ],
        ),
    ]
