# Generated by Django 6.0.5 on 2026-06-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_university_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('conditional', 'Conditional'), ('unconditional', 'Unconditional'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='conditional', max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('acceptance_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.application')),
            ],
        ),
    ]
