# Generated by Django 6.0.5 on 2026-06-17 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_supportticket_ticketcomment'),
        ('core', '0003_task_company'),
        ('leads', '0008_followup_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', '-created_at'], name='app_student_created_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['company', '-created_at'], name='student_company_created_idx'),
        ),
    ]
