# Generated by Django 6.0.5 on 2026-06-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_add_performance_indexes'),
        ('core', '0003_task_company'),
        ('leads', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='app_student_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_company_created_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'is_deleted', '-created_at'], name='app_stu_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['company', 'is_deleted', '-created_at'], name='student_co_del_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student_id',), name='unique_student_id_alive'),
        ),
    ]
