# Generated by Django 6.0.5 on 2026-06-17 23:57

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_student_document'),
        ('core', '0003_task_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('uk_student', 'UK Student'), ('australia_student', 'Australia Student'), ('canada_student', 'Canada Student'), ('germany_student', 'Germany Student'), ('work_visa_applicant', 'Work Visa Applicant')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_certificate', 'Degree Certificate'), ('degree_transcript', 'Degree Transcript'), ('passport', 'Passport'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('sop', 'SOP'), ('lor', 'LOR'), ('resume', 'Resume'), ('bank_statement', 'Bank Statement'), ('sponsor_letter', 'Sponsor Letter'), ('sponsor_id', 'Sponsor ID'), ('income_proof', 'Income Proof'), ('education_loan_letter', 'Education Loan Letter'), ('experience_letter', 'Experience Letter'), ('payslip', 'Payslip'), ('employment_offer_letter', 'Employment Offer Letter'), ('other', 'Other')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='rejection_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_certificate', 'Degree Certificate'), ('degree_transcript', 'Degree Transcript'), ('passport', 'Passport'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('sop', 'SOP'), ('lor', 'LOR'), ('resume', 'Resume'), ('bank_statement', 'Bank Statement'), ('sponsor_letter', 'Sponsor Letter'), ('sponsor_id', 'Sponsor ID'), ('income_proof', 'Income Proof'), ('education_loan_letter', 'Education Loan Letter'), ('experience_letter', 'Experience Letter'), ('payslip', 'Payslip'), ('employment_offer_letter', 'Employment Offer Letter'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=admissions.models.student_document_upload_path),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['company', 'status'], name='studdoc_company_status_idx'),
        ),
        migrations.AddField(
            model_name='documentchecklisttemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='documentchecklisttemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admissions.documentchecklisttemplate'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklisttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_checklist_template_company_code'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklisttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'document_type'), name='uniq_checklist_template_item_type'),
        ),
    ]
