# Generated by Django 6.0.6 on 2026-06-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_student_journey_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchecklisttemplateitem',
            name='document_type',
            field=models.CharField(choices=[('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_certificate', 'Degree Certificate'), ('degree_transcript', 'Degree Transcript'), ('passport', 'Passport'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('sop', 'SOP'), ('lor', 'LOR'), ('resume', 'Resume'), ('university_offer_letter', 'University Offer Letter'), ('bank_statement', 'Bank Statement'), ('sponsor_letter', 'Sponsor Letter'), ('sponsor_id', 'Sponsor ID'), ('income_proof', 'Income Proof'), ('education_loan_letter', 'Education Loan Letter'), ('experience_letter', 'Experience Letter'), ('payslip', 'Payslip'), ('employment_offer_letter', 'Employment Offer Letter'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='admissions.application'),
        ),
    ]
