# Generated by Django 6.0.5 on 2026-06-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0006_leadimportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('preferred_university', models.CharField(blank=True, max_length=255)),
                ('intake', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('counselling', 'Counselling'), ('application', 'Application'), ('offer_received', 'Offer Received'), ('visa_processing', 'Visa Processing'), ('visa_approved', 'Visa Approved'), ('enrolled', 'Enrolled'), ('closed', 'Closed')], default='counselling', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
