# Generated by Django 6.0.5 on 2026-06-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('intake', models.CharField(max_length=100)),
                ('application_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('visa_processing', 'Visa Processing'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student')),
            ],
        ),
    ]
