# Generated by Django 6.0.5 on 2026-06-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('biometrics_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('biometrics_completed', 'Biometrics Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.application')),
            ],
        ),
    ]
