# Generated by Django 6.0.5 on 2026-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_access',
            field=models.BooleanField(default=False),
        ),
    ]
