# Generated by Django 6.0.5 on 2026-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_role_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
