# Generated by Django 6.0.6 on 2026-06-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_alter_documentchecklisttemplateitem_document_type_and_more'),
        ('core', '0004_task_management'),
        ('leads', '0014_lead_timeline_event_type'),
        ('whatsapp', '0002_whatsappserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('follow_up', 'Follow-up'), ('document_reminder', 'Document Reminder'), ('offer_reminder', 'Offer Reminder'), ('visa_update', 'Visa Update')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='admissions.student'),
        ),
        migrations.CreateModel(
            name='WhatsAppReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', '-created_at'], name='wa_reminder_co_created_idx')],
            },
        ),
    ]
