# Generated by Django 6.0.5 on 2026-06-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappmessage_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='wa_msg_company_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='wa_msg_lead_created_idx',
        ),
    ]
