# Generated by Django 6.0.5 on 2026-06-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_company_status_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_company_status_idx',
        ),
    ]
