TICKET_TYPE_BUG = 'bug'
TICKET_TYPE_FEATURE = 'feature'
TICKET_TYPE_INFRA = 'infra'
TICKET_TYPE_SECURITY = 'security'
TICKET_TYPE_ESCALATION = 'escalation'

TICKET_TYPES = (
    TICKET_TYPE_BUG,
    TICKET_TYPE_FEATURE,
    TICKET_TYPE_INFRA,
    TICKET_TYPE_SECURITY,
    TICKET_TYPE_ESCALATION,
)

PRIORITY_LOW = 'low'
PRIORITY_NORMAL = 'normal'
PRIORITY_HIGH = 'high'
PRIORITY_URGENT = 'urgent'

PRIORITIES = (
    PRIORITY_LOW,
    PRIORITY_NORMAL,
    PRIORITY_HIGH,
    PRIORITY_URGENT,
)

STATUS_OPEN = 'open'
STATUS_IN_PROGRESS = 'in_progress'
STATUS_WAITING = 'waiting'
STATUS_RESOLVED = 'resolved'
STATUS_CLOSED = 'closed'

STATUSES = (
    STATUS_OPEN,
    STATUS_IN_PROGRESS,
    STATUS_WAITING,
    STATUS_RESOLVED,
    STATUS_CLOSED,
)

SLA_ON_TRACK = 'on_track'
SLA_AT_RISK = 'at_risk'
SLA_BREACHED = 'breached'

SLA_STATUSES = (
    SLA_ON_TRACK,
    SLA_AT_RISK,
    SLA_BREACHED,
)

TEAM_DEVELOPER = 'developer'
TEAM_SUPPORT = 'support'
TEAM_CS = 'customer_success'
TEAM_FINANCE = 'finance'
TEAM_SALES = 'sales'

TEAMS = (
    TEAM_DEVELOPER,
    TEAM_SUPPORT,
    TEAM_CS,
    TEAM_FINANCE,
    TEAM_SALES,
)

SLA_HOURS = {
    PRIORITY_LOW: 72,
    PRIORITY_NORMAL: 48,
    PRIORITY_HIGH: 24,
    PRIORITY_URGENT: 8,
}

AUDIT_MODULE_OPERATIONS = 'operations'
