# Generated by Django 6.0.5 on 2026-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_branch_lead_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtimeline',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
