# Generated by Django 6.0.5 on 2026-06-17 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_company'),
        ('leads', '0008_followup_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'completed', 'follow_up_date'], name='followup_lead_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='lead_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', '-created_at'], name='lead_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['lead', '-changed_at'], name='auditlog_lead_changed_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtimeline',
            index=models.Index(fields=['lead', '-created_at'], name='timeline_lead_created_idx'),
        ),
    ]
