# Generated by Django 6.0.5 on 2026-06-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_company'),
        ('leads', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_lead_phone_per_company',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_company_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_company_created_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'is_deleted', 'status'], name='lead_co_del_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'is_deleted', '-created_at'], name='lead_co_del_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'phone'), name='unique_lead_phone_alive'),
        ),
    ]
