from django.urls import path

from .api_views import (
    BillingCheckoutAPIView,
    BillingInvoiceListAPIView,
    BillingPaymentListAPIView,
    BillingPortalAPIView,
    CompanySettingsAPIView,
    CompanySubscriptionAPIView,
    CompanyUsageAPIView,
    OnboardingRegisterAPIView,
    OnboardingStepAPIView,
    PlanListAPIView,
    RazorpayWebhookAPIView,
    SaasAdminDashboardAPIView,
    StripeWebhookAPIView,
)
from .platform_views import (
    AdminImpersonateAPIView,
    AdminSupportTicketOpsAPIView,
    AdminTenantActivityAPIView,
    AdminTenantDetailAPIView,
    AdminTenantPlanAPIView,
    AdminTenantResetUsageAPIView,
    AdminTenantTrialAPIView,
    PlatformOperationsAPIView,
)
from .billing_views import (
    CancelSubscriptionAPIView,
    DowngradePlanAPIView,
    PublicBrandingAPIView,
)
from .module_views import CompanyModulesAPIView
from .support_views import (
    AdminSupportTicketListAPIView,
    BrandingUploadAPIView,
    ChangePlanAPIView,
    SupportTicketAttachmentAPIView,
    SupportTicketDetailAPIView,
    SupportTicketListCreateAPIView,
    SupportTicketMessageAPIView,
)

urlpatterns = [
    path('onboard/register/', OnboardingRegisterAPIView.as_view()),
    path('onboard/step/', OnboardingStepAPIView.as_view()),
    path('plans/', PlanListAPIView.as_view()),
    path('subscription/', CompanySubscriptionAPIView.as_view()),
    path('subscription/change-plan/', ChangePlanAPIView.as_view()),
    path('subscription/cancel/', CancelSubscriptionAPIView.as_view()),
    path('subscription/downgrade/', DowngradePlanAPIView.as_view()),
    path('branding/public/', PublicBrandingAPIView.as_view()),
    path('usage/', CompanyUsageAPIView.as_view()),
    path('modules/', CompanyModulesAPIView.as_view()),
    path('settings/', CompanySettingsAPIView.as_view()),
    path('settings/branding/', BrandingUploadAPIView.as_view()),
    path('billing/checkout/', BillingCheckoutAPIView.as_view()),
    path('billing/portal/', BillingPortalAPIView.as_view()),
    path('billing/invoices/', BillingInvoiceListAPIView.as_view()),
    path('billing/payments/', BillingPaymentListAPIView.as_view()),
    path('billing/webhooks/stripe/', StripeWebhookAPIView.as_view()),
    path('billing/webhooks/razorpay/', RazorpayWebhookAPIView.as_view()),
    path('support/tickets/', SupportTicketListCreateAPIView.as_view()),
    path('support/tickets/<int:pk>/', SupportTicketDetailAPIView.as_view()),
    path('support/tickets/<int:pk>/messages/', SupportTicketMessageAPIView.as_view()),
    path('support/tickets/<int:pk>/attachments/', SupportTicketAttachmentAPIView.as_view()),
    path('admin/operations/', PlatformOperationsAPIView.as_view()),
    path('admin/tenants/<int:company_id>/', AdminTenantDetailAPIView.as_view()),
    path('admin/tenants/<int:company_id>/plan/', AdminTenantPlanAPIView.as_view()),
    path('admin/tenants/<int:company_id>/extend-trial/', AdminTenantTrialAPIView.as_view()),
    path('admin/tenants/<int:company_id>/reset-usage/', AdminTenantResetUsageAPIView.as_view()),
    path('admin/tenants/<int:company_id>/activity/', AdminTenantActivityAPIView.as_view()),
    path('admin/support/tickets/<int:pk>/ops/', AdminSupportTicketOpsAPIView.as_view()),
    path('admin/impersonate/<int:user_id>/', AdminImpersonateAPIView.as_view()),
    path('admin/dashboard/', SaasAdminDashboardAPIView.as_view()),
    path('admin/support/tickets/', AdminSupportTicketListAPIView.as_view()),
]
